### ISSUE TITLE
Create Subgraph

### ISSUE THREAD

**Issue by kyriediculous** [Tenderize/tender-app#1]

**Comment by reubenr0d** [comment]
Protocol Page (per Tenderizer)
**Current Principle**
- Timeseries: daily volume
- Timeseries: cumulative 
- Current 

**Reward Collected from protocol**
- Timeseries: daily volume
- Timeseries: cumulative 
- Current 

**Protocol fees collected**
- Timeseries: daily volume
- Timeseries: cumulative 
- Total 

**Protocol Staking APY**
- Timeseries: Daily
- Current

**Liquidity Pool token volume**
- Timeseries: daily volume
- Timeseries: cumulative 
- Current 

**Liquidity Pool tenderToken volume**
- Timeseries: daily volume
- Timeseries: cumulative 
- Current 

**LP Tokens farmed**
- Timeseries: daily volume
- Timeseries: cumulative 
- Current 

**LP fees collected**
- Timeseries: daily volume
- Timeseries: cumulative 
- Total 

**Farming APY**
- Timeseries: Daily
- Current

Wallet/Account page

- Amount deposited per protocol
- Total amount deposited - dollar value only
- Total farmed per Protocol
- Total farmed - dollar value only

Notes/Considerations:
* All token values will be stored with their corresponding dollar values as well?
* Do we want time series data per wallet/user as well?
* Would also be nice to have rewards per user, but might be a little expensive to update on every rebase, I suppose the user can infer that from their tender token balance and we wouldn’t keep track of that?

**Comment by kyriediculous** [comment]
There are three different 'user' types we want to track data for 

- Tender Protocol
- Tenderizer & TenderFarms
- Users 

Let's focus first on Tenderizer and TenderFarms 

Let's also leave USD values out of the picture for now , can always add that later. 

Also we don't need to track all values , let's focus on the necessary ones first.

e.g. APY can be extrapolated from DayData from which the APY can be calculated on a moving average of e.g; 30D, 7D, .. 

### Tenderizer

#### `DayData`

 - Date: "The date beginning at 12:00am UTC"
- StakingRewards: "current staking rewards (0 if no staking rewards in that day)"
- deposit volume: "current deposit volume in this day"
- total deposits (i.e. current principle, i.e. total value locked): "current principle or total value locked"

#### `Tenderizer`

 - totalDeposits: BigDecimal! # Total amount depositied in tenderizer by users
 - totalRewards: BigDecimal! # Total amount staked in protocol
 - protocolFees: Total amount of protocol fees collected by tenderizer
 - liquidityFees: Total amount of protocol fees collected for liquidity pool by tenderizer

### TenderFarm

#### `DayData`

- Date: "The date beginning at 12:00am UTC"
- StakingRewards: "current staking rewards (0 if no staking rewards in that day)"
- deposit volume: "current deposit volume in this day"
- total deposits (i.e. current principle, i.e. total value locked): "current principle or total value locked"

#### `TenderFarm`

 - totalDeposits: BigDecimal! # Total amount depositied in tenderizer by users
 - totalRewards: BigDecimal! # Total amount staked in protocol

### Liquidity Pool

...
