### ISSUE TITLE
Pool token balance shows incorrect in exit pool 

### ISSUE THREAD

**Issue by kyriediculous** [Tenderize/tender-app#117]
![image](https://user-images.githubusercontent.com/22256858/131762830-8a1d0630-a2c0-4690-92db-ff140437e083.png)

![image](https://user-images.githubusercontent.com/22256858/131762853-89ae7b59-c0bd-4fd0-aea5-a01babf8fb43.png)

Exit pool should show 1000 balance as well

**Comment by vujevits** [comment]
on a related note: should we use a uniform naming for the pool token? `POOL tLPT-LPT` vs `tLPT-LPT Pool Token`

**Comment by vujevits** [comment]
@kyriediculous just to make it clearer, I think we should change the wording in the `exit` dialog from **balance** to **staked**, because in fact "Balance: 0.0 tLPT-LPT Pool Token" is a correct statement.

**Comment by kyriediculous** [comment]
Sure
