### ISSUE TITLE
Add ENS support 

### ISSUE THREAD

**Issue by kyriediculous** [Tenderize/tender-app#166]
- Should lookup ENS name for an address
- Should resolve the ENS name to get things like avatar (although this [doesn't seem supported in either ensjs or ethersjs](https://docs.ens.domains/dapp-developer-guide/ens-libraries) at this point out of the box, so would have to write our own resolver)

**Comment by vujevits** [comment]
we are already doing this when on `mainnet`
![image](https://user-images.githubusercontent.com/2270661/148206449-9186f83b-a73e-4f13-a701-bbb4902a7881.png)
