### ISSUE TITLE
Add permit support where possible

### ISSUE THREAD

**Issue by kyriediculous** [Tenderize/tender-app#174]
- [ ] For deposits (add to the stakers data or so which underlying tokens accept permit)
- [x] For swapping (again if the asset is the underlying token would have to add it whether it implements permit) using `Multicall`
- [x] For adding liquidity (both single sided and both tokens) using `Multicall`
- [x] For adding SWAP lp tokens to the `TenderFarm`

**Comment by vujevits** [comment]
resolved by #190 #191 #192
