### ISSUE TITLE
SWAP balances do not appear in account info 

### ISSUE THREAD

**Issue by kyriediculous** [Tenderize/tender-app#239]
<img width="705" alt="image" src="https://user-images.githubusercontent.com/22256858/158442937-48c0803c-4f0b-4673-ba4e-96e8c555cd6c.png">

**Comment by vujevits** [comment]
can you be a bit more specific? It seems to be showing up on my end
<img width="668" alt="Screenshot 2022-03-18 at 9 31 17" src="https://user-images.githubusercontent.com/2270661/158964662-f1136ab8-2288-4e6e-9600-063b44f0e8e6.png">

**Comment by Devjohn12** [comment]
Talk to a Polygon Dev on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into.
