### ISSUE TITLE
Cannot use ERC20Permit with Ledger device

### ISSUE THREAD

**Issue by kyriediculous** [Tenderize/tender-app#272]
**Describe the issue**
When trying to deposit through Tenderize with a token with `ERC20Permit` support (signature based token approvals) the app will throw an exception after signing with a Ledger device. 

![image](https://user-images.githubusercontent.com/22256858/169025090-8c91da29-e3cb-4460-a3b9-2d722757ad7e.png)

This error indicates the *recovery id*  (v param) of the ECDSA signature is incorrect. 

The `v` value for an ECDSA signature in Ethereum should be `27` or `28` according to the Ethereum yellow paper (From [Ethereum's Yellow Paper](https://ethereum.github.io/yellowpaper/paper.pdf) Appendix F - Signing Transactions. The acceptable values for v are 27 or 28.)

However our ledger device seems to return either `0` or `1` for the parameter: `v value: 0`

**Potential solution**
Check if the `v` param from the signature returned from `signERC2612Permit` is either `0` or `1`, if it is hardcode it to be `27` instead. 

```javascript
      if (permit.v === 0 || permit.v === 1) permit.v = 27
```

**Comment by kyriediculous** [comment]
Link T-195

**Comment by vmaark** [comment]
@kyriediculous It's a good hotfix, but shouldn't we open an issue in Ledger / MetaMask too?

**Comment by kyriediculous** [comment]
> @kyriediculous It's a good hotfix, but shouldn't we open an issue in Ledger / MetaMask too? 

It's been an open issue for a long time https://github.com/LedgerHQ/ledgerjs/issues/466
