### ISSUE TITLE
Hooks to fetch data should not fire when on the wrong network

### ISSUE THREAD

**Issue by kyriediculous** [Tenderize/tender-app#281]
Currently a multicall fires to fetch some contract data like token balances even when the user is connected to the wrong network for that particular Tenderizer. You can observe this by opening the developer console and selecting the wrong network and see a stream of errors. Ideally we avoid making these RPC calls.

**Comment by vmaark** [comment]
@kyriediculous since we upgraded the `useDapp` dependency, we could read from the required chains for these calls, even better than disabling!
