### ISSUE TITLE
Subgraph: APY

### ISSUE THREAD

**Issue by reubenr0d** [Tenderize/tender-app#29]
Store the APY for the day every time rewards are collected:
**Tenderizer**
```
day.APY = (previousDayrewards + event.rewards) / event.currentPrinciple * 100
```
- Unlikely, but incase there were multiple rebases during the day, then we also need to account for the rewards that were collected earlier in that day
- FE can use this data to calculate APY over x period
- Days with no rewards will have 0 APY

**Tenderfarm**
```
day.APY = (previousDayHarvest + event.harvestAmount) / (deposits of the users that harvested) * 100
```
Note: previousDayX ie. X that occured previously during the same day
To discuss:
- [ ] Should we account for protocol/liquidity fees as well in the APY?

**Comment by reubenr0d** [comment]
For now, we can just not consider harvests that have happened previously in the day and overwrite APY of the day for the tenderizer based on the latest harvest. Can add it in later if needed

**Comment by kyriediculous** [comment]
This doesn't seem entirely right 

```
day = day.Load(ID)
apy = event.rewards / event.currentPrinciple 
day.apy = day.apy + apy / 2
```

**Comment by kyriediculous** [comment]
For the tenderfarm it's less possible to create it without dollar values because the staking token is not the same as the reward token

**Comment by reubenr0d** [comment]
Revised Formule
Notes:
- We don't want account for the rewards that got auto-compounded during that day, hence use the principle at the start of the day , to discuss
- Tenderfarm: convert value of BPT to tLPT/LPT tokens so that we can calculate APY
**Tenderizer**
```
day.APY = (previous rewards for the day + event.rewards) / principle at day start * 100
```

**Tenderfarm**
```
day.startPrinciple = TenderFarm.totalStake() / ESP.totalSupply() 
day.rewards = Day.Rewards + event. rewards
Day.APY = day.rewards / startPrinciple * 100
```

**Comment by reubenr0d** [comment]
https://github.com/Tenderize/tender-app/pull/30
