### ISSUE TITLE
apy calculation has incorrect compounding

### ISSUE THREAD

**Issue by vmaark** [Tenderize/tender-app#292]
# APY calculation 

## Problem
Currently APY is calculated with the standard APY formula with n = 365, but the compounding events can be non-daily, but whenever a rebase happens. During this we are converting it to daily compounding, which is not correct.

## Solution

Instead of using DPY in the subgraph we replace it by APY. 

The APY would be calculated based on the rewards since the last ClaimRewards event. So it would be the APY at that specific point in time.

Let `d` be the seconds since last rebase with rewards.
No. of compounds in a year `n = 60 * 60 * 24 * 365 / d`

### APY 
r = `rewards since last rebase / currentPrinciple * (yearsInSeconds / timeDiff)` - multiplied to normalize it up to a yearly rewards from a shorter period.

APY based on the timeDiff since the last rebase = 
`(1 + r/n)^n – 1` => 
`(1 + rewards / currentPrincple )^n - 1` 
Because
`(1 + rewards / currentPrincple * (`~~yearsInSeconds / timeDiff~~`) / (`~~yearsInSeconds / timeDiff~~`))^n -1`

Deposits are added to the CP but need not have been staked yet.

On the client side the last x number of APYs datapoints are averaged.

## Notes
APY is calculated using this formula: `APY = (1 + r/n )^n – 1`, where “r” is the stated annual interest rate and “n” is the number of compounding periods each year.

**Comment by kyriediculous** [comment]
Small correction the APY is calculated as 

`(1 + r/n )^n – 1`


or 

$APY = (1 + \frac{r}{n})^n-1$

**Comment by kyriediculous** [comment]
I think the following calculation is easier and more accurate 

$APY = (1 + \frac{r}{n})^n-1$

where

$n = \frac{t_{year}}{t_{elapsed}}$

$r = APR = \frac{rewards}{principle} * n$

____________

So for example we earn 20 rewards on 1000 principle and the time elapsed is 7 days (in practice `t` will be normalized in seconds or milliseconds)

Then 

$n = \frac{t_{year}}{t_{elapsed}}= \frac{365}{7} = 52.14$

and 

$r = APR = \frac{rewards}{principle} * n = \frac{20}{1000}*52= 1.04$ (or 104%)

thus 

$APY = (1 + \frac{r}{n})^n-1 = (1 + \frac{1.04}{52})^{52}-1 = 1.80$ or (180%)

**Comment by vmaark** [comment]
@kyriediculous can we consider this done now? if we identify a new issue we can open a new ticket
