### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by kyriediculous** [Tenderize/tender-app#70]
When the user enters an amount in the form we want to validate the input: 
- amount is a correct decimal number
- amount doesn't exceed balance

**Comment by vujevits** [comment]
> When the user enters an amount in the form we want to validate the input:
> 
> * amount is a correct decimal number
I found good sources for this, and I think we are partly causing the inconsistencies for ourselves:
https://webfocusinfocenter.informationbuilders.com/wfappent/TL2s/TL_nls/source/appc_nls72.htm
> * amount doesn't exceed balance
