### ISSUE TITLE
make the Approve/Swap buttons on the swap tab the same width as those on the stake tab

### ISSUE THREAD

**Issue by vujevits** [Tenderize/tender-app#84]

**Comment by kyriediculous** [comment]
Is this still ongoing or was this fixed in a larger PR ?

**Comment by vujevits** [comment]
> Is this still ongoing or was this fixed in a larger PR ?

it was "fixed", but I realized that now it's broken when there's a spinner. Leave the card open, I'll do a new PR for it.

**Comment by kyriediculous** [comment]
There's a separate issue for that one https://github.com/Tenderize/tender-app/issues/94
