### ISSUE TITLE
Add support for multiple wallets

### ISSUE THREAD

**Issue by kyriediculous** [Tenderize/tender-app#97]
Usedapp allows us to inject `web3-react` functions for different wallet providers: 

https://usedapp.readthedocs.io/en/latest/guide.html#useethers

https://github.com/NoahZinsmeister/web3-react

**Comment by vujevits** [comment]
@kyriediculous Aragon seems like built this on top of `web3-react`:
https://github.com/aragon/use-wallet

**Comment by kyriediculous** [comment]
> @kyriediculous Aragon seems like built this on top of `web3-react`:
> https://github.com/aragon/use-wallet

I'm not sure that works with `useDapp`. See the documentation link. The `activate` raturn parameter from `useEthers` is a function that expects a connector. Since we want this to be injected in `useDapp` we can't use custom hooks from the aragon repo I think.
